// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///

namespace LazyAngus
{
public static class GPGSIds
{
        public const string achievement_wave_10 = "CgkI35efjsIbEAIQAg"; // <GPGSID>
        public const string package_name = "com.lazyangus.lazyangusbeta"; // <GPGSID>
        public const string achievement_double_kill = "CgkI35efjsIbEAIQBQ"; // <GPGSID>
        public const string achievement_wave_5 = "CgkI35efjsIbEAIQAQ"; // <GPGSID>
        public const string leaderboard_top_scores = "CgkI35efjsIbEAIQBw"; // <GPGSID>
        public const string achievement_ultra_kill = "CgkI35efjsIbEAIQCg"; // <GPGSID>
        public const string achievement_wave_40 = "CgkI35efjsIbEAIQBA"; // <GPGSID>
        public const string achievement_triple_kill = "CgkI35efjsIbEAIQCA"; // <GPGSID>
        public const string achievement_wave_20 = "CgkI35efjsIbEAIQAw"; // <GPGSID>
        public const string achievement_quad_kill = "CgkI35efjsIbEAIQCQ"; // <GPGSID>

}
}
