#pragma once
#include <stdint.h>
// Field
struct Field_t5;
// System.Object
#include "mscorlib_System_Object.h"
// Fields
struct  Fields_t6  : public Object_t
{
};
struct Fields_t6_StaticFields{
	// Field Fields::ANONYMIZE_IP
	Field_t5 * ___ANONYMIZE_IP_0;
	// Field Fields::HIT_TYPE
	Field_t5 * ___HIT_TYPE_1;
	// Field Fields::SESSION_CONTROL
	Field_t5 * ___SESSION_CONTROL_2;
	// Field Fields::SCREEN_NAME
	Field_t5 * ___SCREEN_NAME_3;
	// Field Fields::LOCATION
	Field_t5 * ___LOCATION_4;
	// Field Fields::REFERRER
	Field_t5 * ___REFERRER_5;
	// Field Fields::PAGE
	Field_t5 * ___PAGE_6;
	// Field Fields::HOSTNAME
	Field_t5 * ___HOSTNAME_7;
	// Field Fields::TITLE
	Field_t5 * ___TITLE_8;
	// Field Fields::LANGUAGE
	Field_t5 * ___LANGUAGE_9;
	// Field Fields::ENCODING
	Field_t5 * ___ENCODING_10;
	// Field Fields::SCREEN_COLORS
	Field_t5 * ___SCREEN_COLORS_11;
	// Field Fields::SCREEN_RESOLUTION
	Field_t5 * ___SCREEN_RESOLUTION_12;
	// Field Fields::VIEWPORT_SIZE
	Field_t5 * ___VIEWPORT_SIZE_13;
	// Field Fields::APP_NAME
	Field_t5 * ___APP_NAME_14;
	// Field Fields::APP_ID
	Field_t5 * ___APP_ID_15;
	// Field Fields::APP_INSTALLER_ID
	Field_t5 * ___APP_INSTALLER_ID_16;
	// Field Fields::APP_VERSION
	Field_t5 * ___APP_VERSION_17;
	// Field Fields::CLIENT_ID
	Field_t5 * ___CLIENT_ID_18;
	// Field Fields::USER_ID
	Field_t5 * ___USER_ID_19;
	// Field Fields::CAMPAIGN_NAME
	Field_t5 * ___CAMPAIGN_NAME_20;
	// Field Fields::CAMPAIGN_SOURCE
	Field_t5 * ___CAMPAIGN_SOURCE_21;
	// Field Fields::CAMPAIGN_MEDIUM
	Field_t5 * ___CAMPAIGN_MEDIUM_22;
	// Field Fields::CAMPAIGN_KEYWORD
	Field_t5 * ___CAMPAIGN_KEYWORD_23;
	// Field Fields::CAMPAIGN_CONTENT
	Field_t5 * ___CAMPAIGN_CONTENT_24;
	// Field Fields::CAMPAIGN_ID
	Field_t5 * ___CAMPAIGN_ID_25;
	// Field Fields::GCLID
	Field_t5 * ___GCLID_26;
	// Field Fields::DCLID
	Field_t5 * ___DCLID_27;
	// Field Fields::EVENT_CATEGORY
	Field_t5 * ___EVENT_CATEGORY_28;
	// Field Fields::EVENT_ACTION
	Field_t5 * ___EVENT_ACTION_29;
	// Field Fields::EVENT_LABEL
	Field_t5 * ___EVENT_LABEL_30;
	// Field Fields::EVENT_VALUE
	Field_t5 * ___EVENT_VALUE_31;
	// Field Fields::SOCIAL_NETWORK
	Field_t5 * ___SOCIAL_NETWORK_32;
	// Field Fields::SOCIAL_ACTION
	Field_t5 * ___SOCIAL_ACTION_33;
	// Field Fields::SOCIAL_TARGET
	Field_t5 * ___SOCIAL_TARGET_34;
	// Field Fields::TIMING_VAR
	Field_t5 * ___TIMING_VAR_35;
	// Field Fields::TIMING_VALUE
	Field_t5 * ___TIMING_VALUE_36;
	// Field Fields::TIMING_CATEGORY
	Field_t5 * ___TIMING_CATEGORY_37;
	// Field Fields::TIMING_LABEL
	Field_t5 * ___TIMING_LABEL_38;
	// Field Fields::EX_DESCRIPTION
	Field_t5 * ___EX_DESCRIPTION_39;
	// Field Fields::EX_FATAL
	Field_t5 * ___EX_FATAL_40;
	// Field Fields::CURRENCY_CODE
	Field_t5 * ___CURRENCY_CODE_41;
	// Field Fields::TRANSACTION_ID
	Field_t5 * ___TRANSACTION_ID_42;
	// Field Fields::TRANSACTION_AFFILIATION
	Field_t5 * ___TRANSACTION_AFFILIATION_43;
	// Field Fields::TRANSACTION_SHIPPING
	Field_t5 * ___TRANSACTION_SHIPPING_44;
	// Field Fields::TRANSACTION_TAX
	Field_t5 * ___TRANSACTION_TAX_45;
	// Field Fields::TRANSACTION_REVENUE
	Field_t5 * ___TRANSACTION_REVENUE_46;
	// Field Fields::ITEM_SKU
	Field_t5 * ___ITEM_SKU_47;
	// Field Fields::ITEM_NAME
	Field_t5 * ___ITEM_NAME_48;
	// Field Fields::ITEM_CATEGORY
	Field_t5 * ___ITEM_CATEGORY_49;
	// Field Fields::ITEM_PRICE
	Field_t5 * ___ITEM_PRICE_50;
	// Field Fields::ITEM_QUANTITY
	Field_t5 * ___ITEM_QUANTITY_51;
	// Field Fields::TRACKING_ID
	Field_t5 * ___TRACKING_ID_52;
	// Field Fields::SAMPLE_RATE
	Field_t5 * ___SAMPLE_RATE_53;
	// Field Fields::DEVELOPER_ID
	Field_t5 * ___DEVELOPER_ID_54;
	// Field Fields::CUSTOM_METRIC
	Field_t5 * ___CUSTOM_METRIC_55;
	// Field Fields::CUSTOM_DIMENSION
	Field_t5 * ___CUSTOM_DIMENSION_56;
	// Field Fields::ADID
	Field_t5 * ___ADID_57;
	// Field Fields::IDFA
	Field_t5 * ___IDFA_58;
	// Field Fields::ATE
	Field_t5 * ___ATE_59;
};
