// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

public class Accumulator
{
	public int newCount { get; private set; }
	public int derivedCount { get; private set; }

	public Accumulator() {
		newCount = 0;
		derivedCount = 0;
	}

	public void AddNew(int value) {
		newCount += value;
	}
	
	public void AddNew() {
		AddNew (1);
	}
	
	public void AddDerived(int value) {
		derivedCount += value;
	}
	
	public void AddDerived() {
		AddDerived (1);
	}

	public void DeriveFrom(Accumulator accumulator) {
		derivedCount = accumulator.derivedCount + newCount;
	}
}

