// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public class ExplicitMouseDesc
{
	// Type of mouse.
	public MouseConfig.MouseType mouseType;
	// Entry point.
	public MouseHole.MouseHoleLocation mouseHoleLocation;
	// orientation.
	public bool isClockwise;
	// what track it runs on.
	public int track;

	// time until next mouse.
	public float delayToNextMouse;

	// Wiggle type
	public MouseConfig.MouseWiggleType wiggleType;
	public float wiggleMagnitude;
	public float wiggleCycleTime;

	public ExplicitMouseDesc() {
		wiggleType = MouseConfig.MouseWiggleType.NUM_TYPES;
		wiggleMagnitude = 0f;
		wiggleCycleTime = 1f;
	}

	public void AddWiggle(MouseConfig.MouseWiggleType wt) {
		if (wt == wiggleType) {
			return;
		}

		wiggleType = wt;
		MouseWiggleConfig mwc = MouseConfig.instance.GetWiggleConfig (wt);
		wiggleMagnitude = Random.Range (mwc.minMagnitude, 
		                                mwc.maxMagnitude);
		wiggleCycleTime = Random.Range (mwc.minCycleTime, 
		                                mwc.maxCycleTime);
	}
}




