// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System.Collections;

public struct ExplicitMouseDesc
{
	// Type of mouse.
	public MouseConfig.MouseType mouseType;
	// Entry point.
	public MouseHole.MouseHoleLocation mouseHoleLocation;
	// orientation.
	public bool isClockwise;
	// what track it runs on.
	public int track;

	// time until next mouse.
	public float delayToNextMouse;
}


