// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

public class QuasiRandomGenerator<T>
{
	T [] distribution;
	List<T> values;
	public int refreshTrigger = 0;

	public QuasiRandomGenerator (T[] distribution) {
		this.distribution = distribution;
		values = new List<T> ();
	}

	public List<T> RandomizeDistrubiton() {
		List<T> retVal = new List<T> ();
		for (int i = 0; i < distribution.Length; i++) {
			retVal.Add (distribution[i]);
		}
		Utilities.ShuffleList (ref retVal);
		return retVal;
	}

	public T GetNextValue() {
		if (values.Count <= refreshTrigger) {
			RefreshValues();
		}
		T retval = values.ElementAt (0);
		values.RemoveAt (0);
		return retval;
	}

	private void RefreshValues() {
		values = RandomizeDistrubiton ();
	}
}

