// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

public class LazyAngusStrings {

	public const string BOOST_FAIL_LEVEL = "I can't eat that cat food until Wave {0}!";
	public const string BOOST_FAIL_ACTIVE = "I can only eat one cat food at a time!";
	public const string BOOST_FAIL_COST = "Can't affort that!\n\nEarn money by swiping two mice at once!";

	public const string INTRO_BOOST_FAST = "Cat food helps Angus move faster!";
	public const string INTRO_BOOST_SEE = "This cat food helps Angus see better!";
	public const string INTRO_BOOST_GIANT = "Try new Giant Paws cat food!";
	public const string INTRO_BOOST_FART = "This cat food makes me toot!";

	public const string TIP_EXPLAIN_BOOSTS = "Yay, dinner time!\n\nBuy me cat food when you need some extra help!"; 


	public const string TUTORIAL_CATCH_MOUSE = "Yikes! I'd better catch that mouse!";
	public const string TUTORIAL_LEAD_MOUSE = "Lazy cats like me don't move so fast.\n\n" + 
		"Tap in front of a mouse, so I can get there in time!";
	public const string TUTORIAL_DRAG_TURN = "Drag my body to turn me faster!";
	public const string TUTORIAL_TRAPS = "Mousetraps catch mice that get away from me.\n\n" + 
		"But once a trap is sprung, it'd gone for good!";
	public const string TUTORIAL_GAME_OVER = "Oh no!\n\n" + 
		"A mouse got away, it's all over!\n\n" + 
			"Let's try again!";
	public const string TUTORIAL_BOOST_OVER = "The catfood is all gone!\n\nYou can buy me more, but the prices will go up!"; 

	public const string TIP_BOOST_FAST = "Yum! I feel so frisky!\n\n" + 
		"But only for a short time - so let's catch some mice!";
	public const string TIP_BOOST_SEE = "Better eyesight means less turning!";
	public const string TIP_BOOST_GIANT = "No mouse shall escape my mighty paws!";
	public const string TIP_BOOST_FART = "The mice slow down when things get a little stinky...";

}

