#!/usr/bin/python

import shutil
import os
import sys
import time
from mod_pbxproj import *
from os import path, listdir
from shutil import copytree
import sys

from os.path import isfile, join

source_dir = "/Users/douglasbanks/lazyAngus/LazyAngus/Assets/RuntimeResources"
destination_dir = sys.argv[1] + "/RuntimeResources"

f = open("/Users/douglasbanks/tmp/output.txt", "w");
f.write("It's output\n")
f.write("os.getcwd() = " + os.getcwd() + "\n")
ts = time.time()
f.write("TS: " + str(ts) + "\n")
for v in sys.argv: 
	f.write("  v = " + v + "\n")

print "Hello there"
print >> sys.stderr, "Here's an error"
f.write("01\n")
shutil.rmtree(destination_dir, ignore_errors=True)
f.write("02\n")
shutil.copytree(source_dir, destination_dir, symlinks=False, ignore=None)
f.write("03\n")


onlyfiles = [ f for f in listdir(destination_dir) if isfile(join(destination_dir,f)) ]

pbx_file_path = sys.argv[1] + '/Unity-iPhone.xcodeproj/project.pbxproj'
pbx_object = XcodeProject.Load(pbx_file_path)

for f in onlyfiles:
  if not f.endswith(".meta"):
    pbx_object.add_file(destination_dir + "/" + f)


#pbx_object.add_flags([
#  ['ENABLE_BITCODE', ['NO']],
#  ['SHABBA_DOO', ["Howdy"]]])


pbx_object.save()

