#!/usr/bin/python

import shutil
import os
import sys
import time
from mod_pbxproj import *
from os import path, listdir
from shutil import copytree
import sys


pbx_file_path = sys.argv[1] + '/Unity-iPhone.xcodeproj/project.pbxproj'
pbx_object = XcodeProject.Load(pbx_file_path)

pbx_object.add_flags(
  {'ENABLE_BITCODE':'NO'}
)


pbx_object.save()

