#!/usr/bin/python

#Add required libraries to Xcode project during build for Google Analytics
from mod_pbxproj import *
from os import path, listdir
from shutil import copytree
import sys

frameworks = [
              'AdSupport.framework',
              'CoreTelephony.framework',
              'EventKit.framework',
              'EventKitUI.framework',
              'MessageUI.framework',
              'StoreKit.framework',
              'SystemConfiguration.framework',
              'CoreData.framework'
              ]
              
              

libbs = [
              'libz.dylib',
              'libsqlite3.dylib'
              ]
              
framework_dir = path.join(sys.argv[0],'..','..','Plugins','iOS')



pbx_file_path = sys.argv[1] + '/Unity-iPhone.xcodeproj/project.pbxproj'
pbx_object = XcodeProject.Load(pbx_file_path)

pbx_object.add_framework_search_paths([path.abspath(framework_dir)])

for framework in frameworks:
    pbx_object.add_file('System/Library/Frameworks/' + framework, tree='SDKROOT')

for libb in libbs:
    pbx_object.add_file('usr/lib/' + libb, tree='SDKROOT')

pbx_object.save()
